name: cronjob
on: #push
  schedule:
    - cron: "0 0 * * *" # 毎日8時間毎に定期実行(時間がutcなので注意)
jobs:
  toot_gc2:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch #作業ブランチにchekout
        uses: actions/checkout@v2 #サードパーティの公開アクションを利用
        with:
          ref: ${{ github.ref }}
      - name: Git setting
        run: |
          # pullしておかないと Re-run all jobs 実行時はコケてしまうため
          git pull
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit and push
        run: |
          git commit --allow-empty -m "prevent automatic workflow stopping" -m "see: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow"
          git push
      - name: toot gc2
        env:
          ENCODED_ENV: ${{ secrets.ENCODED_ENV }}
        run: |
             echo "start"  
             echo -n ${ENCODED_ENV} | base64 -d > .env
            #  docker-compose up -d
            #  docker-compose exec -T gc2bot python -u main.py
